import { cn } from "../../lib/utils";

/**
 * Tailwind class recipes for the PDF Diff UI.
 *
 * Keeping recipes named by intent gives the component a stable vocabulary
 * while the visual system remains editable in one place. Palette values live
 * in app/globals.css as shadcn CSS variables.
 */
export const styles = {
  root: "min-h-screen bg-background font-sans tracking-[-0.01em] text-foreground",
  shell: "mx-auto flex min-h-screen w-full max-w-[1440px] flex-col",
  topbar: "flex min-h-[72px] items-center justify-between gap-5 border-b border-border bg-card px-8 max-[820px]:px-[18px]",
  topbarActions: "flex items-center gap-3",
  logo: "inline-flex items-center gap-2.5 whitespace-nowrap text-base font-[720] tracking-[-0.04em]",
  logoMark: "grid size-[26px] place-items-center rounded-lg bg-primary text-[15px] font-extrabold tracking-[-0.08em] text-primary-foreground",
  privacyPill: "inline-flex items-center gap-[7px] whitespace-nowrap text-xs font-[590] tracking-[0.01em] text-muted-foreground max-[520px]:hidden",
  privacyDot: "size-[7px] rounded-full bg-success shadow-[0_0_0_3px_hsl(var(--success)/.13)]",
  helpButton: "inline-flex min-h-8 cursor-pointer items-center gap-1.5 rounded-md border border-border bg-transparent px-2.5 text-xs font-[650] text-muted-foreground transition-colors hover:border-foreground/25 hover:bg-secondary hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring",
  helpButtonMark: "grid size-4 place-items-center rounded-full border border-current text-[10px] font-extrabold leading-none",
  intro: "mx-auto flex w-full max-w-[1060px] flex-col items-center px-8 pb-16 pt-[clamp(54px,9vw,116px)] text-center max-[820px]:px-[18px] max-[820px]:pb-[50px] max-[820px]:pt-[54px]",
  eyebrow: "m-0 text-[11px] font-[760] uppercase tracking-[0.17em] text-primary",
  headline: "mt-4 max-w-[720px] text-[clamp(38px,6vw,72px)] font-[730] leading-[0.98] tracking-[-0.075em]",
  headlineAccent: "not-italic text-primary",
  introCopy: "mt-[22px] max-w-[540px] text-base leading-[1.55] text-muted-foreground",
  uploadGrid: "mt-[42px] grid w-full grid-cols-[1fr_auto_1fr] gap-3.5 max-[820px]:grid-cols-1",
  swapUpload: "z-[1] mt-0 size-[42px] cursor-pointer self-center rounded-full border border-border bg-background text-lg font-bold text-primary transition-transform duration-150 hover:rotate-180 hover:bg-accent focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring max-[820px]:mx-auto max-[820px]:my-[-4px]",
  compareButton: "mt-[30px] min-h-[50px] rounded-[11px] bg-primary px-6 text-sm font-[710] text-primary-foreground shadow-[0_7px_16px_hsl(var(--primary)/.18)] transition-[background-color,transform,opacity] duration-150 hover:-translate-y-px hover:bg-primary/90 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-40 disabled:shadow-none",
  errorBox: "mt-[18px] w-full rounded-[10px] border border-destructive/30 bg-destructive/5 px-3.5 py-3 text-left text-[13px] leading-[1.4] text-destructive",
  howTo: "mt-[76px] w-full max-w-[920px] border-t border-border pt-[40px] text-left max-[820px]:mt-[54px]",
  howToHeader: "max-w-[560px]",
  howToTitle: "mt-2 text-[clamp(25px,3vw,38px)] font-[720] leading-[1.05] tracking-[-0.055em]",
  howToCopy: "mt-3 text-sm leading-[1.55] text-muted-foreground",
  howToGrid: "mt-7 grid grid-cols-3 gap-3 max-[700px]:grid-cols-1",
  howToCard: "rounded-xl border border-border bg-card p-4 shadow-[0_6px_16px_hsl(var(--foreground)/.04)]",
  howToStep: "grid size-7 place-items-center rounded-full bg-accent text-xs font-extrabold text-accent-foreground",
  howToCardTitle: "mt-4 text-sm font-bold tracking-[-0.02em]",
  howToCardCopy: "mt-1.5 text-xs leading-[1.5] text-muted-foreground",
  featureGrid: "mt-3 grid grid-cols-3 gap-3 max-[700px]:grid-cols-1",
  featureCard: "rounded-xl border border-border/80 bg-background px-4 py-3.5",
  featureTitle: "text-xs font-bold",
  featureCopy: "mt-1 text-[11px] leading-[1.45] text-muted-foreground",
  srOnly: "absolute size-px overflow-hidden whitespace-nowrap border-0 p-0 [clip:rect(0,0,0,0)] [-webkit-clip-path:inset(50%)] [clip-path:inset(50%)]",
  workspace: "flex min-h-0 flex-1 flex-col",
  workspaceBar: "flex min-h-[68px] items-center justify-between gap-[18px] border-b border-border bg-card px-7 py-3 max-[820px]:px-[18px]",
  documentPair: "flex min-w-0 items-center gap-[11px]",
  documentChip: "flex min-w-0 max-w-[230px] items-center gap-2 rounded-lg border border-border bg-card px-2.5 py-[7px] text-xs font-[620]",
  documentChipLabel: "text-[9px] font-extrabold tracking-[0.08em] text-accent-foreground",
  documentChipName: "min-w-0 overflow-hidden text-ellipsis whitespace-nowrap",
  pairArrow: "text-[17px] font-bold text-primary",
  workspaceActions: "flex items-center gap-2",
  quietButton: "min-h-8 rounded-md border-border px-[11px] text-xs font-[620] text-muted-foreground",
  workspaceMain: "grid min-h-0 flex-1 grid-cols-[112px_minmax(0,1fr)_264px] max-[1100px]:grid-cols-[96px_minmax(0,1fr)_232px] max-[820px]:grid-cols-[76px_minmax(0,1fr)]",
  pageRail: "min-h-0 overflow-y-auto border-r border-sidebar-border bg-sidebar px-3.5 py-[19px]",
  railHeading: "mb-[13px] mt-0 px-0.5 text-[10px] font-[760] uppercase tracking-[0.12em] text-sidebar-foreground",
  pageButton: "mb-2.5 w-full cursor-pointer rounded-lg border border-transparent bg-transparent p-[5px] text-left text-sidebar-foreground transition-colors hover:bg-card focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring",
  pageButtonCurrent: "border-primary bg-accent",
  pageThumb: "relative aspect-[0.71] overflow-hidden rounded border border-border bg-background shadow-[0_2px_4px_hsl(var(--foreground)/.05)]",
  pageThumbImage: "block size-full object-cover",
  thumbPlaceholder: "flex size-full flex-col gap-1 bg-card p-[7px]",
  thumbLine: "h-0.5 rounded bg-success/30",
  thumbLineShort: "w-[62%]",
  thumbDiagram: "mt-0.5 flex-1 border border-success/20 bg-success/5",
  pageNumber: "mt-[5px] flex items-center justify-between gap-[5px] px-0.5 text-[10px] font-[680]",
  pageStatus: "inline-flex items-center gap-[3px] text-[9px] text-success",
  pageStatusChanged: "text-primary",
  pageStatusAdded: "text-success",
  pageStatusRemoved: "text-destructive",
  canvasColumn: "flex min-h-0 min-w-0 flex-col bg-stage",
  toolbar: "flex min-h-[58px] flex-wrap items-center justify-between gap-3 border-b border-border bg-secondary px-4 py-2 max-[820px]:flex-wrap",
  toolbarGroup: "flex items-center gap-1.5",
  modeGroup: "flex items-center gap-0.5 rounded-lg border border-border bg-muted p-[3px]",
  modeButton: "min-h-7 cursor-pointer whitespace-nowrap rounded-md border-0 bg-transparent px-[9px] text-[11px] font-[650] text-muted-foreground hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring",
  modeButtonCurrent: "bg-card text-foreground shadow-[0_1px_3px_hsl(var(--foreground)/.11)]",
  sourceGroup: "flex items-center gap-0.5 rounded-lg border border-border bg-card p-[3px]",
  sourceButton: "inline-flex min-h-7 cursor-pointer items-center gap-1 whitespace-nowrap rounded-md border-0 bg-transparent px-2 text-[11px] font-[650] text-muted-foreground hover:bg-accent hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-35",
  sourceButtonCurrent: "bg-accent text-accent-foreground",
  iconButton: "grid size-[30px] cursor-pointer place-items-center rounded-md border border-border bg-card text-[15px] font-[620] leading-none text-muted-foreground hover:border-foreground/30 hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-40",
  zoomLabel: "min-w-[45px] text-center text-[11px] tabular-nums text-muted-foreground",
  stage: "relative min-h-[300px] flex-1 overflow-auto bg-stage p-[clamp(26px,5vw,58px)] [background-image:radial-gradient(hsl(var(--stage-dot))_0.7px,transparent_0.7px)] [background-size:15px_15px]",
  stageCenter: "flex min-h-full min-w-full items-start justify-center",
  paper: "relative min-h-[520px] w-[min(780px,100%)] origin-top overflow-hidden bg-background shadow-[0_18px_36px_hsl(var(--foreground)/.17),0_3px_7px_hsl(var(--foreground)/.09)] transition-transform duration-200",
  paperZoom50: "scale-50",
  paperZoom75: "scale-75",
  paperZoom100: "scale-100",
  paperZoom125: "scale-[1.25]",
  paperZoom150: "scale-150",
  paperZoom200: "scale-[2]",
  pageImage: "block h-auto min-h-[520px] w-full select-none object-contain",
  diffImage: "block h-auto min-h-[520px] w-full select-none object-contain",
  sideBySide: "grid min-h-[520px] grid-cols-2 gap-px bg-stage",
  sidePanel: "min-w-0 overflow-hidden bg-background",
  paperEmpty: "grid min-h-[520px] place-items-center p-[30px] text-center text-[13px] text-muted-foreground",
  placeholderArt: "absolute inset-0 flex flex-col gap-[13px] px-[12%] py-[14%] opacity-70",
  placeholderTitle: "mb-2 h-[7px] w-[42%] rounded bg-success/30",
  placeholderRule: "h-0.5 w-full bg-success/15",
  placeholderRuleShort: "w-[67%]",
  placeholderBoxGrid: "grid min-h-[170px] flex-1 grid-cols-2 gap-[15px]",
  placeholderBox: "border border-success/20 bg-success/5",
  placeholderFooter: "mt-[15px] h-[3px] w-3/4 rounded bg-success/15",
  changeOverlay: "pointer-events-auto absolute cursor-pointer border-2 border-primary bg-primary/10 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring",
  changeOverlayAdded: "border-success bg-success/10",
  changeOverlayRemoved: "border-destructive bg-destructive/10",
  changeOverlayCurrent: "shadow-[0_0_0_3px_hsl(var(--primary)/.2)]",
  swipeWrap: "relative overflow-hidden",
  swipeNewer: "pointer-events-none absolute inset-0 size-full object-contain",
  swipeHandle: "pointer-events-auto absolute bottom-0 top-0 z-[1] flex w-6 -translate-x-1/2 cursor-col-resize touch-none items-center justify-center focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring",
  swipe50: "[clip-path:inset(0_50%_0_0)]",
  swipe60: "[clip-path:inset(0_40%_0_0)]",
  swipe70: "[clip-path:inset(0_30%_0_0)]",
  swipe80: "[clip-path:inset(0_20%_0_0)]",
  swipe90: "[clip-path:inset(0_10%_0_0)]",
  swipe100: "[clip-path:inset(0_0%_0_0)]",
  swipe0: "[clip-path:inset(0_100%_0_0)]",
  swipe10: "[clip-path:inset(0_90%_0_0)]",
  swipe20: "[clip-path:inset(0_80%_0_0)]",
  swipe30: "[clip-path:inset(0_70%_0_0)]",
  swipe40: "[clip-path:inset(0_60%_0_0)]",
  swipeDivider: "pointer-events-none absolute bottom-0 top-0 w-0.5 bg-primary shadow-[0_0_0_1px_rgb(255_255_255_/_0.55)]",
  blinkBadge: "absolute right-3.5 top-3.5 rounded-md bg-foreground/75 px-2 py-[5px] text-[10px] font-bold uppercase tracking-[0.06em] text-background",
  canvasCaption: "absolute bottom-[15px] left-[17px] inline-flex items-center gap-[7px] rounded-md border border-foreground/15 bg-card/85 px-[9px] py-1.5 text-[10px] font-semibold text-muted-foreground",
  captionDotAdded: "size-[7px] rounded-full bg-success",
  captionDotRemoved: "size-[7px] rounded-full bg-destructive",
  inspector: "min-h-0 overflow-y-auto border-l border-border bg-card/60 px-[18px] py-[21px] max-[820px]:hidden",
  inspectorHeading: "m-0 text-sm font-bold tracking-[-0.02em]",
  inspectorSubheading: "mb-[18px] mt-[5px] text-[11px] leading-[1.4] text-muted-foreground",
  changeSummary: "mb-[22px] grid grid-cols-2 gap-[7px]",
  statCard: "rounded-lg border border-border bg-card px-[11px] py-2.5",
  statLabel: "text-[10px] font-[620] text-muted-foreground",
  statValue: "mt-1 block text-[18px] font-[720] tabular-nums text-success-ink",
  statValueWarm: "text-primary",
  inspectorSection: "mt-[17px] border-t border-border pt-[17px]",
  sectionLabel: "mb-2.5 flex items-center justify-between text-[10px] font-[760] uppercase tracking-[0.13em] text-muted-foreground",
  changeList: "flex flex-col gap-1.5",
  changeButton: "flex w-full cursor-pointer items-center gap-2 rounded-md border border-border bg-card px-2.5 py-[9px] text-left text-[11px] font-[620] text-foreground transition-colors hover:border-primary/50 hover:bg-accent focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring",
  changeButtonCurrent: "border-primary bg-accent",
  changeDot: "size-[7px] shrink-0 rounded-full bg-primary",
  changeDotAdded: "bg-success",
  changeDotRemoved: "bg-destructive",
  changeText: "min-w-0 overflow-hidden text-ellipsis whitespace-nowrap",
  changeCount: "ml-auto text-[10px] tabular-nums text-muted-foreground",
  emptyChanges: "rounded-lg border border-dashed border-border px-2.5 py-4 text-[11px] leading-[1.45] text-muted-foreground",
  controlRow: "mb-3 flex items-center justify-between gap-3",
  controlName: "text-[11px] font-[620] text-muted-foreground",
  controlValue: "text-[11px] font-bold tabular-nums text-foreground",
  switchRow: "mb-3 flex items-center justify-between gap-3 rounded-lg border border-border bg-card px-2.5 py-2",
  switchLabel: "text-[11px] font-[620] text-foreground",
  switch: "relative inline-flex h-5 w-9 shrink-0 items-center rounded-full border border-input bg-muted transition-colors focus-within:ring-2 focus-within:ring-ring focus-within:ring-offset-1",
  switchOn: "border-primary bg-primary",
  switchInput: "absolute inset-0 z-[1] size-full cursor-pointer opacity-0",
  switchThumb: "pointer-events-none block size-3.5 translate-x-0.5 rounded-full bg-background shadow-sm transition-transform",
  switchThumbOn: "translate-x-[17px]",
  select: "min-h-[30px] max-w-[135px] cursor-pointer rounded-md border border-input bg-card px-2 text-[11px] font-[620] text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring",
  range: "w-[120px] cursor-pointer accent-primary",
  statusFooter: "flex min-h-9 items-center justify-between gap-3 border-t border-border bg-secondary px-[18px] text-[10px] font-[570] text-muted-foreground",
  statusAccent: "text-success",
  shortcutHint: "hidden text-[10px] text-muted-foreground max-[1180px]:hidden",
  fullPageBackdrop: "fixed inset-0 z-50 grid place-items-center bg-foreground/75 p-4 backdrop-blur-sm max-[520px]:p-0",
  fullPageDialog: "flex h-[min(94vh,1100px)] w-[min(96vw,1200px)] flex-col overflow-hidden rounded-xl border border-border bg-card shadow-[0_24px_80px_hsl(var(--foreground)/.3)] max-[520px]:h-full max-[520px]:w-full max-[520px]:rounded-none",
  fullPageToolbar: "flex min-h-[68px] items-center justify-between gap-4 border-b border-border bg-card px-5 py-3 max-[520px]:px-3.5",
  fullPageHeading: "min-w-0",
  fullPageTitle: "m-0 text-sm font-bold tracking-[-0.02em]",
  fullPageFileName: "mt-1 max-w-[min(44vw,520px)] overflow-hidden text-ellipsis whitespace-nowrap text-[11px] text-muted-foreground",
  fullPageActions: "flex shrink-0 items-center gap-2 max-[720px]:gap-1",
  fullPagePageNav: "flex items-center gap-1",
  fullPagePagePosition: "min-w-[74px] text-center text-[10px] tabular-nums text-muted-foreground max-[520px]:hidden",
  fullPageClose: "ml-1 size-8 text-lg",
  fullPageStage: "flex min-h-0 flex-1 items-start justify-center overflow-auto bg-stage p-[clamp(18px,4vw,52px)] [background-image:radial-gradient(hsl(var(--stage-dot))_0.7px,transparent_0.7px)] [background-size:15px_15px]",
  fullPageImage: "block h-auto max-h-full max-w-full select-none object-contain shadow-[0_12px_30px_hsl(var(--foreground)/.18)]",
  fullPageFooter: "flex min-h-9 flex-wrap items-center justify-between gap-x-3 gap-y-1 border-t border-border bg-secondary px-5 py-1.5 text-[10px] text-muted-foreground max-[520px]:px-3.5",
  helpDialog: "flex max-h-[min(88vh,780px)] w-[min(92vw,820px)] flex-col overflow-hidden rounded-xl border border-border bg-card shadow-[0_24px_80px_hsl(var(--foreground)/.3)] max-[520px]:max-h-full max-[520px]:h-full max-[520px]:w-full max-[520px]:rounded-none",
  helpHeader: "flex shrink-0 items-start justify-between gap-5 border-b border-border bg-card px-6 py-5 max-[520px]:px-4",
  helpEyebrow: "m-0 text-[10px] font-[760] uppercase tracking-[0.14em] text-primary",
  helpTitle: "mt-1.5 text-xl font-bold tracking-[-0.04em]",
  helpLead: "mt-1.5 max-w-[560px] text-xs leading-[1.5] text-muted-foreground",
  helpClose: "size-8 shrink-0 text-lg",
  helpBody: "min-h-0 overflow-y-auto px-6 py-6 max-[520px]:px-4",
  helpSection: "not-first:mt-7",
  helpSectionTitle: "m-0 text-xs font-[760] uppercase tracking-[0.12em] text-muted-foreground",
  helpSteps: "mt-3 grid grid-cols-3 gap-3 max-[680px]:grid-cols-1",
  helpStep: "rounded-lg border border-border bg-background p-3.5",
  helpStepTitle: "mt-3 text-sm font-bold tracking-[-0.02em]",
  helpStepCopy: "mt-1.5 text-xs leading-[1.5] text-muted-foreground",
  helpFeatureGrid: "mt-3 grid grid-cols-2 gap-2 max-[620px]:grid-cols-1",
  helpFeature: "rounded-lg border border-border bg-background px-3.5 py-3",
  helpFeatureTitle: "text-xs font-bold",
  helpFeatureCopy: "mt-1 text-[11px] leading-[1.45] text-muted-foreground",
  helpModeList: "mt-3 grid grid-cols-2 gap-x-5 gap-y-2 text-xs max-[620px]:grid-cols-1",
  helpMode: "leading-[1.45] text-muted-foreground",
  helpModeName: "font-bold text-foreground",
  helpShortcutGrid: "mt-3 grid grid-cols-2 gap-x-5 gap-y-2 max-[620px]:grid-cols-1",
  helpShortcut: "flex items-start gap-2 text-[11px] leading-[1.45] text-muted-foreground",
  helpKey: "shrink-0 rounded border border-border bg-secondary px-1.5 py-0.5 font-mono text-[10px] font-bold text-foreground",
  helpNote: "mt-6 rounded-lg border border-success/25 bg-success/5 px-3.5 py-3 text-xs leading-[1.5] text-success-ink",
  helpFooter: "flex shrink-0 items-center justify-between gap-3 border-t border-border bg-secondary px-6 py-3 text-[11px] text-muted-foreground max-[520px]:px-4",
  loading: "grid min-h-[440px] flex-1 place-items-center p-[30px]",
  loadingCard: "w-[min(390px,100%)] rounded-[14px] border border-border bg-card p-[25px] text-center shadow-[0_12px_25px_hsl(var(--foreground)/.08)]",
  loadingMark: "mx-auto grid size-[42px] place-items-center rounded-full border-2 border-primary/30 border-t-primary text-[15px] text-primary animate-[spin_900ms_linear_infinite]",
  loadingTitle: "mt-[17px] text-[17px] font-bold",
  loadingCopy: "mt-[7px] text-xs leading-[1.5] text-muted-foreground",
  progressLabel: "text-[11px] text-muted-foreground",
  progressTrack: "mt-[18px] h-[5px] overflow-hidden rounded-[5px] bg-secondary",
  progressFill: "h-full rounded-[5px] bg-primary transition-[width] duration-200",
  busyBar: "min-h-1 bg-secondary",
  busyBarFill: "h-full bg-primary transition-[width] duration-200",
  mobileOnly: "hidden max-[820px]:inline",
  desktopOnly: "inline max-[820px]:hidden",
} as const;

export type TailwindClass = string | false | null | undefined;

export const styleProps = (...stylesToApply: Array<TailwindClass>) => ({
  className: cn(...stylesToApply),
});
