import { ui } from "@pdfdiff/viewer-react";

export { styleProps, type TailwindClass } from "@pdfdiff/viewer-react";
export { ui };

/** One page gutter and one content width for every screen, marketing or legal. */
const gutter = "px-8 max-[820px]:px-5";
const container = "mx-auto w-full max-w-[1120px]";

export const styles = {
  root: "min-h-screen bg-background font-sans tracking-tight text-foreground",
  shell: "flex min-h-screen w-full flex-col",
  topbar: `${gutter} flex min-h-[72px] items-center justify-between gap-5 border-b border-border bg-card`,
  logo: "inline-flex items-center gap-2.5 whitespace-nowrap text-base font-semibold tracking-tight text-foreground no-underline",
  logoMark: "grid size-[26px] place-items-center rounded-lg bg-primary text-sm font-semibold text-primary-foreground",
  intro: `${gutter} ${container} grid grid-cols-[minmax(0,460px)_minmax(0,1fr)] items-center gap-x-14 gap-y-10 pb-16 pt-[clamp(36px,4.5vw,60px)] max-[980px]:grid-cols-1 max-[980px]:text-center max-[820px]:pb-12 max-[820px]:pt-10`,
  introMain: "flex flex-col items-start max-[980px]:items-center",
  eyebrow: `${ui.caps} m-0 text-primary`,
  headline: "text-[clamp(32px,4vw,48px)] font-semibold leading-[1.05] tracking-tighter",
  headlineAccent: "not-italic text-primary",
  uploadGrid: "mt-8 grid w-full grid-cols-[1fr_auto_1fr] gap-3.5 max-[820px]:grid-cols-1",
  swapUpload: `${ui.control} ${ui.focus} z-[1] size-[42px] self-center rounded-full bg-background text-lg font-bold text-primary transition-transform duration-150 hover:rotate-180 hover:bg-accent hover:text-primary max-[820px]:mx-auto max-[820px]:-my-1`,
  rememberOption: `${ui.card} mt-4 flex w-full cursor-pointer items-start gap-3 px-4 py-3.5 text-left transition-colors hover:border-foreground/30`,
  rememberCheckbox: `${ui.focus} pdfdiff-switch mt-0.5`,
  rememberTitle: "block text-sm font-medium text-foreground",
  rememberCopy: "mt-0.5 block text-xs leading-[1.5] text-muted-foreground",
  introActions: "mt-4 flex flex-wrap items-center gap-4 max-[980px]:justify-center",
  compareButton: "min-h-12 px-6",
  privacyNote: "inline-flex items-center gap-2 text-xs leading-relaxed text-muted-foreground",
  privacyDot: "size-1.5 shrink-0 rounded-full bg-success",
  errorBox: "mt-4 w-full rounded-xl border border-destructive/30 bg-destructive/5 px-3.5 py-3 text-left text-xs leading-[1.5] text-destructive",
  history: `${gutter} ${container} mb-16 w-full text-left`,
  historyHeader: "flex items-end justify-between gap-4",
  historyTitle: "m-0 text-[clamp(19px,2.2vw,24px)] font-semibold leading-tight tracking-tight",
  historyList: "mt-5 grid gap-2.5",
  historyCard: `${ui.card} grid grid-cols-[minmax(0,1fr)_auto] items-center gap-x-5 gap-y-2 px-4 py-3.5 max-[650px]:grid-cols-1`,
  historyFiles: "flex min-w-0 items-center gap-2 text-sm",
  historyFileName: "min-w-0 truncate font-medium",
  historyArrow: "shrink-0 text-primary",
  historyMeta: "flex flex-wrap gap-x-4 gap-y-1 text-2xs text-muted-foreground",
  historyResume: "col-start-2 row-span-2 row-start-1 max-[650px]:col-start-1 max-[650px]:row-span-1 max-[650px]:row-start-auto max-[650px]:justify-self-start",
  historyNote: "mt-3 text-xs leading-relaxed text-muted-foreground",
  demo: `${ui.card} w-full overflow-hidden text-left`,
  demoBar: "flex items-center gap-2 border-b border-border bg-card px-3 py-2.5 text-2xs",
  demoChip: "min-w-0 truncate rounded-lg border border-border bg-background px-2 py-1 font-medium",
  demoArrow: "shrink-0 text-primary",
  demoCount: "ml-auto shrink-0 rounded-lg bg-primary/10 px-2 py-1 font-medium text-primary max-[560px]:hidden",
  demoStage: "grid place-items-center bg-stage p-[clamp(10px,2vw,22px)]",
  demoPage: "block h-auto w-full max-w-[300px] rounded-sm border border-border shadow-sm",
  demoSplit: "grid w-full grid-cols-2 gap-2",
  demoSwipe: "relative w-full max-w-[300px]",
  demoSwipeTop: "pdfdiff-swipe-top absolute inset-0",
  demoSwipeHandle: "pdfdiff-swipe-handle absolute inset-y-0 w-px -translate-x-1/2 bg-primary",
  demoFoot: "flex flex-wrap items-center gap-x-4 gap-y-2 border-t border-border bg-card px-3 py-2.5",
  demoTabs: "inline-flex gap-1",
  demoTab: `${ui.control} ${ui.focus} min-h-7 border-transparent bg-transparent px-2.5 text-2xs`,
  demoTabCurrent: "border-border bg-background text-foreground",
  demoCaption: "min-w-0 flex-1 text-2xs leading-[1.5] text-muted-foreground max-[560px]:basis-full",
  footer: `${gutter} mt-auto border-t border-border bg-card`,
  footerInner: `${container} flex min-h-16 items-center justify-end`,
  footerLinks: "flex flex-wrap items-center gap-x-5 gap-y-2",
  footerLink: `${ui.focus} text-xs font-medium text-muted-foreground underline-offset-4 transition-colors hover:text-foreground hover:underline focus-visible:ring-offset-2 focus-visible:ring-offset-card`,
  loading: "grid min-h-[440px] flex-1 place-items-center p-8",
  loadingCard: `${ui.card} w-[min(390px,100%)] p-6 text-center`,
  loadingPreview: "relative mx-auto h-24 w-28 animate-pulse motion-reduce:animate-none",
  loadingPage: `${ui.card} absolute left-1 top-3 flex h-20 w-16 flex-col gap-2 p-3 shadow-sm`,
  loadingPageAfter: "left-auto right-1 top-0 bg-accent",
  loadingLine: "h-1 rounded-full bg-muted-foreground/20",
  loadingLineShort: "w-2/3",
  loadingBlock: "mt-auto h-7 rounded-lg bg-secondary",
  loadingChange: "mt-auto h-7 rounded-lg border border-border bg-primary/10",
  loadingTitle: "mt-4 text-lg font-semibold tracking-tight",
  loadingCopy: "mt-2 text-xs leading-[1.5] text-muted-foreground",
  loadingCancel: "mt-4",
  /** Legal pages: same shell, narrower measure. */
  legalArticle: `${gutter} mx-auto w-full max-w-[800px] flex-1 pb-20 pt-[clamp(48px,7vw,82px)]`,
  legalBack: `${ui.focus} rounded-lg text-sm font-medium text-muted-foreground no-underline hover:text-foreground`,
  legalHeader: "mt-8 border-b border-border pb-10",
  legalTitle: "mt-3 text-[clamp(34px,5vw,52px)] font-semibold leading-[1.05] tracking-tighter",
  legalUpdated: "mt-4 text-sm text-muted-foreground",
  legalBody: "mt-10 grid gap-9",
  legalSection: "border-t border-border pt-8 first:border-0 first:pt-0",
  legalSectionTitle: "m-0 text-xl font-semibold tracking-tight",
  legalProse: "mt-3 grid gap-3 text-base leading-7 text-muted-foreground",
  legalLead: "text-base leading-7 text-muted-foreground",
  legalCallout: "rounded-xl border border-success/30 bg-success/5 px-5 py-4 text-base leading-7 text-foreground",
  legalList: "m-0 grid gap-2 pl-5",
  legalLink: `${ui.focus} rounded-sm text-primary underline underline-offset-4`,
} as const;
