import { twMerge } from "tailwind-merge";

export const styles = {
  workspaceBar: "flex h-14 min-h-14 items-center justify-between gap-4 border-b border-border/80 bg-card px-5 max-[820px]:px-3.5",
  logo: "inline-flex items-center gap-2 whitespace-nowrap text-sm font-[720] tracking-[-0.03em]",
  logoMark: "grid size-6 place-items-center rounded-lg bg-primary text-sm font-extrabold tracking-[-0.08em] text-primary-foreground",
  documentPair: "flex min-w-0 items-center gap-2",
  documentChip: "flex min-w-0 max-w-[220px] items-center gap-2 rounded-lg border border-border/80 bg-background px-2.5 py-1.5 text-xs font-[620]",
  documentChipLabel: "text-[9px] font-extrabold tracking-[0.08em] text-accent-foreground",
  documentChipName: "min-w-0 overflow-hidden text-ellipsis whitespace-nowrap",
  pairArrow: "text-base font-bold text-primary/80",
  workspaceActions: "flex items-center gap-1.5",
  quietButton: "inline-flex min-h-8 items-center justify-center rounded-lg border border-border/80 bg-transparent px-2.5 text-xs font-[620] text-muted-foreground transition-colors hover:bg-secondary hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring",
  helpButton: "inline-flex min-h-8 cursor-pointer items-center gap-1.5 rounded-lg border border-border/80 bg-transparent px-2.5 text-xs font-[650] text-muted-foreground transition-colors hover:bg-secondary hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring",
  helpButtonMark: "grid size-4 place-items-center rounded-full border border-current text-[10px] font-extrabold leading-none",
  workspaceMain: "grid min-h-0 flex-1 grid-cols-[170px_minmax(0,1fr)_44px] max-[980px]:grid-cols-[150px_minmax(0,1fr)_44px] max-[820px]:grid-cols-[150px_minmax(0,1fr)]",
  workspaceMainInspectorOpen: "grid-cols-[170px_minmax(0,1fr)_304px] max-[1180px]:grid-cols-[160px_minmax(0,1fr)_288px] max-[980px]:grid-cols-[150px_minmax(0,1fr)_272px] max-[820px]:grid-cols-[150px_minmax(0,1fr)]",
  pageRail: "min-h-0 overflow-y-auto overflow-x-hidden border-r border-sidebar-border/80 bg-sidebar px-2.5 py-4",
  railHeader: "mb-3 flex flex-col gap-2",
  railTitleRow: "flex items-center justify-between gap-2 px-0.5",
  railHeading: "m-0 px-0.5 text-[10px] font-[760] uppercase tracking-[0.12em] text-sidebar-foreground",
  railPageButton: "grid size-7 cursor-pointer place-items-center rounded-lg border border-border/80 bg-card text-[13px] font-[620] leading-none text-muted-foreground transition-colors hover:border-foreground/30 hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-40",
  railPagePosition: "min-w-0 flex-1 text-center text-[10px] tabular-nums text-sidebar-foreground",
  unifiedPageNavigation: "flex flex-col gap-1 rounded-xl border border-border/80 bg-card p-1",
  unifiedPageRow: "grid grid-cols-[28px_minmax(0,1fr)_28px] items-center gap-1",
  unifiedPagePosition: "grid min-w-0 grid-cols-[18px_minmax(0,1fr)] items-center gap-1 rounded-lg bg-secondary/70 px-1.5 py-1 text-[10px] tabular-nums text-sidebar-foreground [&_strong]:text-center [&_strong]:font-[680]",
  unifiedPageLabel: "grid size-[18px] place-items-center rounded-md bg-primary/10 text-[9px] font-extrabold text-primary",
  railFilterGroup: "grid grid-cols-2 gap-1 border-t border-sidebar-border/80 pt-2",
  railFilterButton: "flex min-h-8 min-w-0 items-center justify-center gap-1 rounded-lg border border-transparent px-1 text-[10px] font-[650] text-muted-foreground transition-colors hover:bg-card hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring",
  sourceRail: "flex flex-col gap-1 border-t border-sidebar-border/80 pt-2",
  sourceRailHeading: "whitespace-nowrap px-0.5 text-[9px] font-[760] uppercase tracking-[0.1em] text-sidebar-foreground",
  pageButton: "mb-2 w-full cursor-pointer rounded-lg border border-transparent bg-transparent p-1.5 text-left text-sidebar-foreground transition-colors hover:bg-card/75 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring",
  pageButtonCurrent: "border-primary/60 bg-accent shadow-[0_1px_2px_hsl(var(--foreground)/.05)]",
  pageThumb: "relative aspect-[0.72] overflow-hidden rounded-lg border border-border/80 bg-background shadow-[0_2px_5px_hsl(var(--foreground)/.08)]",
  pageThumbImage: "block size-full bg-white object-contain",
  thumbPlaceholder: "flex size-full flex-col gap-1 bg-card p-[7px]",
  thumbLine: "h-0.5 rounded bg-success/30",
  thumbLineShort: "w-[62%]",
  thumbDiagram: "mt-0.5 flex-1 border border-success/20 bg-success/5",
  pageNumber: "mt-1 flex items-center justify-between gap-1 px-0.5 text-[10px] font-[680]",
  pageStatus: "inline-flex items-center gap-[3px] text-[9px] text-success",
  pageStatusChanged: "text-primary",
  pageStatusAdded: "text-success",
  pageStatusRemoved: "text-destructive",
  canvasColumn: "flex min-h-0 min-w-0 flex-col bg-stage",
  toolbar: "flex min-h-12 flex-wrap items-center justify-between gap-2 border-b border-border/80 bg-card px-4 py-1.5 max-[820px]:flex-wrap max-[560px]:px-2.5",
  toolbarGroup: "flex items-center gap-1.5",
  modeGroup: "flex min-w-0 items-center gap-0.5 overflow-x-auto rounded-lg border border-border/80 bg-muted p-0.5",
  modeButton: "min-h-8 cursor-pointer whitespace-nowrap rounded-lg border-0 bg-transparent px-2 text-[11px] font-[650] text-muted-foreground transition-colors hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring",
  modeButtonCurrent: "bg-card text-foreground shadow-[0_1px_3px_hsl(var(--foreground)/.1)]",
  sourceGroup: "flex items-center gap-0.5 rounded-lg border border-border/80 bg-card p-0.5",
  sourceButton: "inline-flex min-h-8 cursor-pointer items-center gap-1 whitespace-nowrap rounded-lg border-0 bg-transparent px-2 text-[11px] font-[650] text-muted-foreground transition-colors hover:bg-accent hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-35",
  sourcePageGroup: "flex items-center gap-0.5 rounded-lg border border-border/80 bg-card p-0.5",
  sourcePageGroupCompact: "grid w-full grid-cols-[14px_24px_minmax(38px,1fr)_24px_24px] items-center rounded-lg border border-border/80 bg-card p-0.5",
  sourcePageLabel: "px-1 text-[10px] font-[760] uppercase tracking-[0.08em] text-muted-foreground",
  sourcePageLabelCompact: "px-0.5 text-[9px] tracking-[0.05em]",
  sourcePageButton: "grid size-8 cursor-pointer place-items-center rounded-lg border-0 bg-transparent text-[14px] font-[620] leading-none text-muted-foreground transition-colors hover:bg-accent hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-35",
  sourcePageButtonCompact: "size-6 text-[12px]",
  sourcePagePosition: "min-w-[43px] text-center text-[10px] tabular-nums text-muted-foreground",
  sourcePagePositionCompact: "min-w-0 whitespace-nowrap text-[9px]",
  sourceButtonCompact: "min-h-0 size-6 justify-center px-1 text-[12px]",
  previewStack: "flex w-[min(820px,100%)] flex-col gap-2",
  iconButton: "grid size-8 cursor-pointer place-items-center rounded-lg border border-border/80 bg-card text-[15px] font-[620] leading-none text-muted-foreground transition-colors hover:border-foreground/30 hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-40",
  zoomLabel: "min-w-[45px] text-center text-[11px] tabular-nums text-muted-foreground",
  stage: "relative min-h-[300px] flex-1 overflow-auto bg-stage p-[clamp(20px,4vw,48px)]",
  stageCenter: "flex min-h-full min-w-full items-start justify-center",
  paper: "relative min-h-[520px] w-[min(820px,100%)] origin-top overflow-hidden bg-background shadow-[0_16px_36px_hsl(var(--foreground)/.14),0_2px_6px_hsl(var(--foreground)/.08)] ring-1 ring-foreground/5",
  paperZoom50: "scale-50",
  paperZoom75: "scale-75",
  paperZoom100: "scale-100",
  paperZoom125: "scale-[1.25]",
  paperZoom150: "scale-150",
  paperZoom200: "scale-[2]",
  pageImage: "block h-auto min-h-[520px] w-full select-none object-contain",
  diffImage: "block h-auto min-h-[520px] w-full select-none object-contain",
  actionButton: "mt-1 min-h-11 w-full cursor-pointer rounded-lg border-0 bg-primary px-4 text-sm font-[710] text-primary-foreground shadow-[0_5px_12px_hsl(var(--primary)/.16)] transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring",
  sideBySide: "grid min-h-[520px] grid-cols-2 gap-px bg-stage",
  sidePanel: "min-w-0 overflow-hidden bg-background",
  paperEmpty: "grid min-h-[520px] place-items-center p-[30px] text-center text-[13px] text-muted-foreground",
  placeholderTitle: "mb-2 inline-block h-[7px] w-[42%] rounded bg-success/30",
  changeOverlay: "pointer-events-auto absolute cursor-pointer border border-primary/45 bg-primary/5 transition-[border-color,background-color,box-shadow] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring",
  changeOverlayAdded: "border-success/50 bg-success/5",
  changeOverlayRemoved: "border-destructive/50 bg-destructive/5",
  changeOverlayCurrent: "border-primary bg-primary/12 shadow-[0_0_0_3px_hsl(var(--primary)/.18)]",
  swipeWrap: "relative overflow-hidden",
  swipeSizer: "block h-auto min-h-[520px] w-full select-none object-contain opacity-0",
  swipeLayer: "pointer-events-none absolute inset-0 z-0 overflow-hidden",
  swipeLayerImage: "block h-auto min-h-[520px] w-full select-none object-contain",
  swipeHandle: "pointer-events-auto absolute bottom-0 top-0 z-[1] flex w-6 -translate-x-1/2 cursor-col-resize touch-none items-center justify-center focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring",
  swipeDivider: "pointer-events-none absolute bottom-0 top-0 w-0.5 bg-primary shadow-[0_0_0_1px_rgb(255_255_255_/_0.55)]",
  blinkBadge: "absolute right-3.5 top-3.5 rounded-md bg-foreground/75 px-2 py-[5px] text-[10px] font-bold uppercase tracking-[0.06em] text-background",
  semanticPaper: "min-h-[520px] overflow-hidden bg-card",
  semanticSummary: "flex items-center justify-between gap-3 border-b border-border bg-secondary px-5 py-3 text-[11px] font-[650] text-muted-foreground",
  semanticLegend: "flex flex-wrap items-center gap-x-3 gap-y-1 border-b border-border bg-card px-5 py-2 text-[10px] font-[620] text-muted-foreground",
  semanticLegendDot: "mr-1 inline-block size-2 rounded-full align-[-1px]",
  semanticLegendAdded: "bg-success",
  semanticLegendRemoved: "bg-destructive",
  semanticLegendChanged: "bg-primary",
  semanticLegendNote: "ml-auto max-[700px]:basis-full",
  semanticGrid: "grid min-h-[470px] grid-cols-2 gap-px bg-stage max-[700px]:grid-cols-1",
  semanticColumn: "min-w-0 bg-background",
  semanticHeader: "flex items-center justify-between gap-3 border-b border-border bg-card px-5 py-3 text-[10px] font-[760] uppercase tracking-[0.1em] text-muted-foreground",
  semanticViewport: "relative w-full overflow-hidden bg-white",
  semanticPageImage: "relative z-0 block h-auto w-full select-none",
  semanticOverlay: "pointer-events-none absolute inset-0 z-[1] size-full overflow-visible",
  semanticOverlayPolygon: "pointer-events-auto cursor-pointer stroke-1 opacity-40 outline-none transition-[opacity,filter] focus-visible:opacity-90 focus-visible:brightness-90",
  semanticOverlayAdded: "fill-success stroke-success",
  semanticOverlayRemoved: "fill-destructive stroke-destructive",
  semanticOverlayChanged: "fill-primary stroke-primary",
  semanticOverlayCurrent: "opacity-85 stroke-foreground [stroke-width:1.5]",
  semanticNoText: "border-t border-border bg-secondary px-5 py-3 text-xs text-muted-foreground",
  changeOverlayLegend: "absolute bottom-4 left-4 inline-flex items-center gap-1.5 rounded-lg border border-foreground/10 bg-card/90 px-2.5 py-1.5 text-[10px] font-semibold text-muted-foreground shadow-sm",
  inspector: "min-h-0 border-l border-border/80 bg-card max-[820px]:hidden",
  inspectorOpen: "overflow-y-auto px-4 py-4",
  inspectorCollapsed: "flex items-start justify-center overflow-hidden py-3",
  inspectorCollapsedButton: "inline-flex min-h-24 w-8 cursor-pointer items-center justify-center rounded-lg border border-border/80 bg-transparent py-2 text-[10px] font-[720] tracking-[0.04em] text-muted-foreground transition-colors [writing-mode:vertical-rl] rotate-180 hover:border-primary/50 hover:bg-accent hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring",
  inspectorHeader: "flex items-center justify-between gap-3",
  inspectorHeading: "m-0 text-[13px] font-bold tracking-[-0.015em]",
  inspectorSubheading: "mb-4 mt-1 text-[11px] leading-[1.45] text-muted-foreground",
  changeSummary: "mb-4 grid grid-cols-2 gap-2",
  statCard: "rounded-lg border border-border/80 bg-background px-2.5 py-2.5",
  statLabel: "text-[10px] font-[620] text-muted-foreground",
  statValue: "mt-1 block text-[18px] font-[720] tabular-nums text-success-ink",
  statValueWarm: "text-primary",
  inspectorSection: "mt-4 border-t border-border/80 pt-4",
  sectionLabel: "mb-2.5 flex items-center justify-between text-[10px] font-[760] uppercase tracking-[0.13em] text-muted-foreground",
  changeList: "flex flex-col gap-1",
  changeButton: "flex min-h-9 w-full cursor-pointer items-center gap-2 rounded-lg border border-border/80 bg-background px-2.5 py-2 text-left text-[11px] font-[620] text-foreground transition-colors hover:border-primary/50 hover:bg-accent focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring",
  changeButtonCurrent: "border-primary/70 bg-accent",
  changeDot: "size-[7px] shrink-0 rounded-full bg-primary",
  changeDotAdded: "bg-success",
  changeDotRemoved: "bg-destructive",
  changeText: "min-w-0 overflow-hidden text-ellipsis whitespace-nowrap",
  changeCount: "ml-auto text-[10px] tabular-nums text-muted-foreground",
  emptyChanges: "rounded-lg border border-dashed border-border px-2.5 py-4 text-[11px] leading-[1.45] text-muted-foreground",
  controlRow: "mb-3 flex items-center justify-between gap-3",
  controlName: "text-[11px] font-[620] text-muted-foreground",
  controlValue: "text-[11px] font-bold tabular-nums text-foreground",
  switchRow: "mb-3 flex items-center justify-between gap-3 rounded-lg border border-border/80 bg-background px-2.5 py-2",
  switchLabel: "text-[11px] font-[620] text-foreground",
  switch: "relative inline-flex h-5 w-9 shrink-0 items-center rounded-full border border-input bg-muted transition-colors focus-within:ring-2 focus-within:ring-ring focus-within:ring-offset-1",
  switchOn: "border-primary bg-primary",
  switchInput: "absolute inset-0 z-[1] size-full cursor-pointer opacity-0",
  switchThumb: "pointer-events-none block size-3.5 translate-x-0.5 rounded-full bg-background shadow-sm transition-transform",
  switchThumbOn: "translate-x-[17px]",
  select: "min-h-8 max-w-[135px] cursor-pointer rounded-lg border border-input bg-background px-2 text-[11px] font-[620] text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring",
  range: "w-[120px] cursor-pointer accent-primary",
  statusFooter: "flex min-h-9 items-center justify-between gap-3 border-t border-border/80 bg-card px-4 text-[10px] font-[570] text-muted-foreground",
  statusAccent: "text-success",
  shortcutHint: "hidden text-[10px] text-muted-foreground max-[1180px]:hidden",
  fullPageBackdrop: "fixed inset-0 z-50 grid place-items-center bg-foreground/75 p-4 backdrop-blur-sm max-[520px]:p-0",
  fullPageDialog: "flex h-[min(94vh,1100px)] w-[min(96vw,1200px)] flex-col overflow-hidden rounded-lg border border-border bg-card shadow-[0_24px_80px_hsl(var(--foreground)/.3)] max-[520px]:h-full max-[520px]:w-full max-[520px]:rounded-none",
  fullPageToolbar: "flex min-h-14 items-center justify-between gap-4 border-b border-border bg-card px-5 py-2 max-[520px]:px-3.5",
  fullPageHeading: "min-w-0",
  fullPageTitle: "m-0 text-sm font-bold tracking-[-0.02em]",
  fullPageFileName: "mt-1 max-w-[min(44vw,520px)] overflow-hidden text-ellipsis whitespace-nowrap text-[11px] text-muted-foreground",
  fullPageActions: "flex shrink-0 items-center gap-2 max-[720px]:gap-1",
  fullPagePageNav: "flex items-center gap-1",
  fullPagePagePosition: "min-w-[74px] text-center text-[10px] tabular-nums text-muted-foreground max-[520px]:hidden",
  fullPageClose: "ml-1 size-8 text-lg",
  fullPageStage: "flex min-h-0 flex-1 items-start justify-center overflow-auto bg-stage p-[clamp(18px,4vw,52px)]",
  fullPageImage: "block h-auto max-h-full max-w-full select-none object-contain shadow-[0_12px_30px_hsl(var(--foreground)/.18)]",
  fullPageFooter: "flex min-h-9 flex-wrap items-center justify-between gap-x-3 gap-y-1 border-t border-border bg-secondary px-5 py-1.5 text-[10px] text-muted-foreground max-[520px]:px-3.5",
  helpDialog: "flex max-h-[min(88vh,780px)] w-[min(92vw,820px)] flex-col overflow-hidden rounded-lg border border-border bg-card shadow-[0_24px_80px_hsl(var(--foreground)/.3)] max-[520px]:max-h-full max-[520px]:h-full max-[520px]:w-full max-[520px]:rounded-none",
  helpHeader: "flex shrink-0 items-start justify-between gap-5 border-b border-border bg-card px-6 py-5 max-[520px]:px-4",
  helpEyebrow: "m-0 text-[10px] font-[760] uppercase tracking-[0.14em] text-primary",
  helpTitle: "mt-1.5 text-xl font-bold tracking-[-0.04em]",
  helpLead: "mt-1.5 max-w-[560px] text-xs leading-[1.5] text-muted-foreground",
  helpBody: "min-h-0 overflow-y-auto px-6 py-6 max-[520px]:px-4",
  helpSection: "not-first:mt-7",
  helpSectionTitle: "m-0 text-xs font-[760] uppercase tracking-[0.12em] text-muted-foreground",
  helpSteps: "mt-3 grid grid-cols-3 gap-3 max-[680px]:grid-cols-1",
  helpStep: "rounded-lg border border-border bg-background p-3.5",
  helpStepTitle: "mt-3 text-sm font-bold tracking-[-0.02em]",
  helpStepCopy: "mt-1.5 text-xs leading-[1.5] text-muted-foreground",
  helpModeList: "mt-3 grid grid-cols-2 gap-x-5 gap-y-2 text-xs max-[620px]:grid-cols-1",
  helpMode: "leading-[1.45] text-muted-foreground",
  helpModeName: "font-bold text-foreground",
  helpShortcutGrid: "mt-3 grid grid-cols-2 gap-x-5 gap-y-2 max-[620px]:grid-cols-1",
  helpShortcut: "flex items-start gap-2 text-[11px] leading-[1.45] text-muted-foreground",
  helpKey: "shrink-0 rounded border border-border bg-secondary px-1.5 py-0.5 font-mono text-[10px] font-bold text-foreground",
  helpNote: "mt-6 rounded-lg border border-success/25 bg-success/5 px-3.5 py-3 text-xs leading-[1.5] text-success-ink",
  helpFooter: "flex shrink-0 items-center justify-between gap-3 border-t border-border bg-secondary px-6 py-3 text-[11px] text-muted-foreground max-[520px]:px-4",
  mobileOnly: "hidden max-[820px]:inline",
  desktopOnly: "inline max-[820px]:hidden",
} as const;

export type TailwindClass = string | false | null | undefined;
export const styleProps = (...values: TailwindClass[]) => ({ className: twMerge(values.filter(Boolean).join(" ")) });
