import { twMerge } from "tailwind-merge";

/**
 * Design system, such as it is: tokens live in theme.css, these five strings are
 * the shared patterns, and every style below composes them. Nothing else should
 * hand-roll a focus ring, a card border, or an uppercase label.
 */
export const ui = {
  focus: "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring",
  /** Uppercase section label: eyebrows, group titles, column headers. */
  caps: "text-3xs font-semibold uppercase tracking-caps text-muted-foreground",
  /** Any raised surface on the page background. */
  card: "rounded-xl border border-border bg-card",
  /** Any clickable chrome that is not the primary button. */
  control: "inline-flex cursor-pointer items-center justify-center gap-1.5 whitespace-nowrap rounded-lg border border-border bg-card text-2xs font-medium text-muted-foreground transition-colors hover:border-foreground/30 hover:text-foreground disabled:cursor-not-allowed disabled:opacity-40",
  /** Modal panel; pair with dialogBackdrop. */
  dialog: "flex flex-col overflow-hidden rounded-xl border border-border bg-card shadow-lg",
} as const;

export const styles = {
  viewerRoot: "flex h-screen min-h-0 flex-none flex-col",
  workspaceBar: "flex h-13 min-h-13 shrink-0 items-center justify-between gap-4 max-[820px]:gap-2 border-b border-border bg-card px-5 max-[820px]:px-3.5",
  logo: "inline-flex items-center gap-2 whitespace-nowrap text-sm font-semibold tracking-tight",
  logoMark: "grid size-6 place-items-center rounded-lg bg-primary text-sm font-semibold text-primary-foreground",
  documentPair: "flex min-w-0 items-center gap-2 max-[820px]:hidden",
  documentChip: "flex min-w-0 max-w-[220px] items-center gap-2 rounded-lg border border-border bg-background px-2.5 py-1.5 text-xs font-medium",
  documentChipLabel: `${ui.caps} text-accent-foreground`,
  documentChipName: "min-w-0 overflow-hidden text-ellipsis whitespace-nowrap",
  pairArrow: "text-base font-bold text-primary/80",
  headerSummary: "ml-auto flex min-w-0 items-center gap-2 text-2xs max-[560px]:hidden",
  headerHeadline: "truncate text-2xs font-medium text-foreground",
  headerWarning: "shrink-0 rounded-lg bg-primary/10 px-2 py-1 text-2xs font-medium text-primary",
  workspaceActions: "flex items-center gap-1.5",
  quietButton: `${ui.control} ${ui.focus} min-h-8 px-2.5 hover:bg-secondary`,
  helpButton: `${ui.control} ${ui.focus} min-h-8 px-2.5 hover:bg-secondary`,
  helpButtonMark: "grid size-4 place-items-center rounded-full border border-current text-3xs font-semibold leading-none",
  workspaceMain: "grid min-h-0 flex-1 grid-cols-[170px_minmax(0,1fr)] max-[980px]:grid-cols-[150px_minmax(0,1fr)] max-[820px]:grid-cols-1 max-[820px]:grid-rows-[minmax(0,1fr)_auto]",
  workspaceMainSinglePage: "grid-cols-1",
  pageRail: "min-h-0 overflow-y-auto overflow-x-hidden border-r border-sidebar-border bg-sidebar px-2.5 py-4 max-[820px]:order-2 max-[820px]:flex max-[820px]:items-center max-[820px]:gap-2 max-[820px]:overflow-x-auto max-[820px]:overflow-y-hidden max-[820px]:border-r-0 max-[820px]:border-t max-[820px]:px-2 max-[820px]:py-2",
  railHeader: "mb-3 flex flex-col gap-2 max-[820px]:mb-0 max-[820px]:shrink-0",
  railHeading: `${ui.caps} m-0 px-0.5 text-sidebar-foreground max-[820px]:hidden`,
  railPageButton: `${ui.control} ${ui.focus} size-7 p-0 text-xs`,
  unifiedPageNavigation: `${ui.card} flex flex-col gap-1 p-1`,
  unifiedPageRow: "grid grid-cols-[28px_minmax(0,1fr)_28px] items-center gap-1",
  unifiedPagePosition: "grid min-w-0 grid-cols-[18px_minmax(0,1fr)] items-center gap-1 rounded-lg bg-secondary/70 px-1.5 py-1 text-3xs tabular-nums text-sidebar-foreground [&_strong]:text-center [&_strong]:font-medium",
  unifiedPageLabel: "grid size-[18px] place-items-center rounded-md bg-primary/10 text-3xs font-semibold text-primary",
  pageButton: `${ui.focus} mb-2 w-full max-[820px]:mb-0 max-[820px]:w-[72px] max-[820px]:shrink-0 cursor-pointer rounded-xl border border-transparent bg-transparent p-1.5 text-left text-sidebar-foreground transition-colors hover:bg-card/75`,
  pageButtonCurrent: "border-primary/60 bg-accent",
  exportWrap: "relative",
  exportMenu: `${ui.card} absolute right-0 top-full z-20 mt-1 flex w-56 flex-col overflow-hidden bg-popover shadow-lg`,
  exportItem: `${ui.focus} cursor-pointer border-0 bg-transparent px-3 py-2 text-left text-2xs font-medium text-foreground transition-colors hover:bg-accent focus-visible:bg-accent`,
  railNote: "px-1 py-2 text-center text-3xs text-muted-foreground max-[820px]:shrink-0",
  filterChip: `${ui.control} ${ui.focus} min-h-7 bg-background px-2.5 hover:bg-accent`,
  filterChipOn: "border-primary/60 bg-accent text-foreground",
  pageBadge: "absolute left-1 top-1 rounded-md bg-foreground/75 px-1.5 py-0.5 text-3xs font-bold uppercase tracking-caps text-background",
  pageThumb: "relative aspect-[0.72] overflow-hidden rounded-lg border border-border bg-background",
  pageThumbImage: "block size-full bg-white object-contain",
  thumbPlaceholder: "flex size-full flex-col gap-1 bg-card p-[7px]",
  thumbLine: "h-0.5 rounded bg-success/30",
  thumbLineShort: "w-[62%]",
  thumbDiagram: "mt-0.5 flex-1 border border-success/20 bg-success/5",
  pageNumber: "mt-1 flex items-center justify-between gap-1 px-0.5 text-3xs font-medium",
  pageStatus: "inline-flex items-center gap-[3px] text-3xs text-success",
  pageStatusChanged: "text-primary",
  pageStatusAdded: "text-success",
  pageStatusRemoved: "text-destructive",
  canvasColumn: "flex min-h-0 min-w-0 flex-col bg-stage max-[820px]:order-1",
  toolbar: "flex min-h-12 flex-wrap items-center justify-between gap-2 border-b border-border bg-card px-4 py-1.5 max-[560px]:px-2.5",
  toolbarGroup: "flex flex-wrap items-center gap-1.5",
  modeGroup: "flex min-w-0 items-center gap-0.5 overflow-x-auto rounded-lg border border-border bg-muted p-0.5",
  modeButton: `${ui.control} ${ui.focus} min-h-8 border-transparent bg-transparent px-2 disabled:opacity-35`,
  modeButtonCurrent: "border-border bg-card text-foreground",
  iconButton: `${ui.control} ${ui.focus} size-8 p-0 text-sm`,
  zoomLabel: "min-w-[45px] text-center text-2xs tabular-nums text-muted-foreground",
  stage: "relative min-h-[300px] flex-1 touch-none cursor-grab overflow-hidden bg-stage p-[clamp(12px,2vw,28px)] select-none",
  stagePanning: "cursor-grabbing",
  stageCenter: "flex min-h-full min-w-full items-start justify-center",
  stageContent: "will-change-transform [transform-origin:center_top]",
  /** The base layer is a translucent greyscale render, so the page needs paper under it in both themes. */
  layerStack: "relative block h-auto w-full bg-white",
  layerBase: "block h-auto w-full",
  layerTint: "pointer-events-none absolute inset-0",
  overlaySwatch: "pdfdiff-swatch",
  overlayRange: "pdfdiff-range w-32",
  overlayLabel: "text-2xs font-medium text-muted-foreground",
  paper: "relative mx-auto min-h-[min(520px,45vh)] w-[min(820px,100%)] origin-top overflow-hidden rounded-xl border border-border bg-background",
  /** Two-up modes get two page columns, so the paper doubles: a page is the same size at a given zoom in every mode. */
  paperTwoUp: "w-[min(1660px,100%)]",
  pageImage: "block h-auto min-h-[min(520px,45vh)] w-full select-none object-contain",
  diffImage: "block h-auto min-h-[min(520px,45vh)] w-full select-none object-contain",
  sideBySide: "grid min-h-[min(520px,45vh)] grid-cols-2 gap-px bg-stage",
  sidePanel: "min-w-0 overflow-hidden bg-background",
  paperEmpty: "grid min-h-[min(520px,45vh)] place-items-center p-[30px] text-center text-xs text-muted-foreground",
  placeholderTitle: "mb-2 inline-block h-[7px] w-[42%] rounded bg-success/30",
  changeOverlay: `${ui.focus} pointer-events-auto absolute cursor-pointer border border-primary/45 bg-primary/5 transition-[border-color,background-color,box-shadow]`,
  changeOverlayAdded: "border-success/50 bg-success/5",
  changeOverlayRemoved: "border-destructive/50 bg-destructive/5",
  changeOverlayCurrent: "border-primary bg-primary/12 ring-2 ring-primary/25",
  swipeWrap: "relative overflow-hidden",
  swipeSizer: "block h-auto min-h-[min(520px,45vh)] w-full select-none object-contain opacity-0",
  swipeLayer: "pointer-events-none absolute inset-0 z-0 overflow-hidden",
  swipeLayerImage: "block h-auto min-h-[min(520px,45vh)] w-full select-none object-contain",
  swipeHandle: `${ui.focus} pointer-events-auto absolute bottom-0 top-0 z-[1] flex w-6 -translate-x-1/2 cursor-col-resize touch-none items-center justify-center`,
  swipeDivider: "pointer-events-none absolute bottom-0 top-0 w-0.5 bg-primary ring-1 ring-white/60",
  semanticPaper: "min-h-[min(520px,45vh)] overflow-hidden bg-card",
  semanticSummary: "flex items-center justify-between gap-3 border-b border-border bg-secondary px-5 py-3 text-2xs font-medium text-muted-foreground",
  semanticLegend: "flex flex-wrap items-center gap-x-3 gap-y-1 border-b border-border bg-card px-5 py-2 text-3xs font-medium text-muted-foreground",
  semanticLegendDot: "mr-1 inline-block size-2 rounded-full align-[-1px]",
  semanticLegendAdded: "bg-success",
  semanticLegendRemoved: "bg-destructive",
  semanticLegendChanged: "bg-primary",
  semanticLegendNote: "ml-auto max-[700px]:basis-full",
  semanticGrid: "grid min-h-[min(470px,45vh)] grid-cols-2 gap-px bg-stage max-[700px]:grid-cols-1",
  semanticColumn: "min-w-0 bg-background",
  semanticHeader: `${ui.caps} border-b border-border bg-card px-5 py-3`,
  semanticViewport: "relative w-full overflow-hidden bg-white",
  semanticPageImage: "relative z-0 block h-auto w-full select-none",
  semanticOverlay: "pointer-events-none absolute inset-0 z-[1] size-full overflow-visible",
  semanticOverlayPolygon: "pointer-events-auto cursor-pointer stroke-1 opacity-40 outline-none transition-[opacity,filter] focus-visible:opacity-90 focus-visible:brightness-90",
  semanticOverlayAdded: "fill-success stroke-success",
  semanticOverlayRemoved: "fill-destructive stroke-destructive",
  semanticOverlayChanged: "fill-primary stroke-primary",
  semanticOverlayCurrent: "opacity-85 stroke-foreground [stroke-width:1.5]",
  semanticNoText: "border-t border-border bg-secondary px-5 py-3 text-xs text-muted-foreground",
  changeOverlayLegend: "pointer-events-none absolute bottom-4 left-4 inline-flex items-center gap-2.5 rounded-lg border border-border bg-card px-2.5 py-1.5 text-3xs font-semibold text-muted-foreground",
  changeOverlayKey: "inline-flex items-center gap-1",
  changeOverlayDot: "size-2 rounded-full",
  statusFooter: "flex min-h-9 items-center border-t border-border bg-card px-4 text-3xs font-medium text-muted-foreground",
  statusAccent: "text-success",
  dialogBackdrop: "fixed inset-0 z-50 grid place-items-center bg-foreground/50 p-4 backdrop-blur-sm max-[520px]:p-0",
  settingsDialog: `${ui.dialog} max-h-[min(88vh,640px)] w-[min(92vw,420px)]`,
  settingsBody: "min-h-0 overflow-y-auto px-5 py-5",
  settingsGroup: "not-first:mt-6",
  settingsGroupTitle: `${ui.caps} m-0`,
  settingsRow: "mt-3 flex items-center justify-between gap-3 text-xs font-medium text-foreground",
  settingsNote: "mt-2 text-2xs leading-relaxed text-muted-foreground",
  settingsCheckbox: `${ui.focus} pdfdiff-switch`,
  helpDialog: `${ui.dialog} max-h-[min(88vh,780px)] w-[min(92vw,820px)] max-[520px]:h-full max-[520px]:max-h-full max-[520px]:w-full max-[520px]:rounded-none`,
  helpHeader: "flex shrink-0 items-start justify-between gap-5 border-b border-border bg-card px-6 py-5 max-[520px]:px-4",
  helpTitle: "m-0 text-xl font-semibold tracking-tight",
  helpBody: "min-h-0 overflow-y-auto px-6 py-6 max-[520px]:px-4",
  helpSection: "not-first:mt-7",
  helpSectionTitle: `${ui.caps} m-0`,
  helpSteps: "mt-3 grid grid-cols-3 gap-3 max-[680px]:grid-cols-1",
  helpStep: "rounded-xl border border-border bg-background p-3.5",
  helpStepTitle: "mt-3 text-sm font-semibold tracking-tight",
  helpStepCopy: "mt-1.5 text-xs leading-[1.5] text-muted-foreground",
  helpModeList: "mt-3 grid grid-cols-2 gap-x-5 gap-y-2 text-xs max-[620px]:grid-cols-1",
  helpMode: "leading-[1.45] text-muted-foreground",
  helpModeName: "font-semibold text-foreground",
  helpShortcutGrid: "mt-3 grid grid-cols-2 gap-x-5 gap-y-2 max-[620px]:grid-cols-1",
  helpShortcut: "flex items-start gap-2 text-2xs leading-[1.45] text-muted-foreground",
  helpKey: "shrink-0 rounded-md border border-border bg-secondary px-1.5 py-0.5 font-mono text-3xs font-semibold text-foreground",
  helpNote: "mt-6 rounded-xl border border-success/25 bg-success/5 px-3.5 py-3 text-xs leading-[1.5] text-success-ink",
  helpFooter: "flex shrink-0 items-center justify-end border-t border-border bg-secondary px-6 py-3 max-[520px]:px-4",
} as const;

export type TailwindClass = string | false | null | undefined;
export const styleProps = (...values: TailwindClass[]) => ({ className: twMerge(values.filter(Boolean).join(" ")) });
